
site_name: PyPSA China (PIK) #(PIK edition) Documentation

theme:
  name: "material"
  logo: "assets/img/logo_small.png"
  favicon: "assets/img/pypsa_china.ico"
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      # primary: deep purple
      accent: blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: amber

docs_dir: "./docs"

# Due to snakemake workflow, we need to include the 'scripts' directory in the python path
plugins:
  - gen-files:
      scripts:
      - docs/autogen_ref_pages.py
  # - literate-nav:
  #     nav_file: reference_nav.yml
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["./workflow/scripts"]
  - search
  - awesome-nav:
      keep_order: true
      collapse_single_pages: false
      auto_nav: false
nav:
  - .nav.yaml

extra_css:
  - docs/assets/styles/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: &copy Potsdam Institute for Climate Impact Research (PIK) 2024