
site_name: PyPSA China Model (PIK edition) Documentation

theme:
  name: "material"
docs_dir: "./docs"

# Due to snakemake workflow, we need to include the 'scripts' directory in the python path
plugins:
  - gen-files:
      scripts:
      - docs/autogen_ref_pages.py
  - literate-nav:
      nav_file: reference_nav.yml
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["./workflow/scripts"]
  - search

nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - Reference:
      - reference.md

