# SPDX-FileCopyrightText: : 2022 The PyPSA-China Authors
#
# SPDX-License-Identifier: CC0-1.0
# DO NOT FORGET TO LOOK AT THE TECHNOLOGY CONFIGURATION FILES

run:
  name: existinginfra_chp_converted_05x_cheaperwind
foresight: "overnight"

paths:
  results_dir: "results/"
  summary_dir: "summary/" # TODO useless?
  costs_dir: "resources/data/costs/EUR_wind_2x_cheaper"
  yearly_regional_load: 
    ac: "resources/data/load/Provincial_Load_2020_2060_MWh.csv"
    # conversion factor to MWh in case ac load file in another unit
    ac_to_mwh: 1

io:
  nc_compression:
    level: 4
    zlib: True
    
scenario: 
  co2_pathway: ["exp175default"] # co2_scenarios that will be used
  topology: "current+FCG" # "current" or "FCG" or "current+FCG" or "current+Neighbor"
  planning_horizons:
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050
    - 2055
    - 2060
  heating_demand: ["positive"]

co2_scenarios: 
  exp175default:
    control: "reduction" # price | reduction | budget | None
    pathway:
      '2020': 0.0
      '2025': 0.22623418
      '2030': 0.41175086
      '2035': 0.56387834
      '2040': 0.688626
      '2045': 0.79092165
      '2050': 0.87480618
      '2055': 0.94359322
      '2060': 1.0

# TODO Need to test timezones and functionality of end_year_plus1
snapshots:
  start: "01-01 00:00"
  end: "12-31 23:00"
  bounds: 'both'
  freq: '1h'
  # test weighings -> to be improved
  frequency: 1.
  # in case snapshots cross the planning horizon year
  end_year_plus1: false

logging_level: INFO
logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

enable:
  build_cutout: false
  retrieve_cutout: false
  retrieve_raster: false

atlite:
  cutout_name: "China-2020c"
  freq: "h"
  nprocesses: 1
  show_progress: true
  monthly_requests: true
  cutouts:
    China-2020c:
      module: era5
      dx: 0.25
      dy: 0.25
      weather_year: 2020
    China-tests-cutout:
      module: era5
      dx: 5
      dy: 5
      weather_year: 2020

renewable:
  onwind:
    cutout: China-2020c
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    # bin by capacity factor
    resource_classes:
      min_cf_delta: 0.05
      n: 3  
    capacity_per_sqkm: 3 # ScholzPhd Tab 4.3.1: 10MW/km^2
    potential: simple # or conservative
    natura: false
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2
  offwind:
    cutout: China-2020c
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    resource_classes:
      min_cf_delta: 0.05
      n: 3
    capacity_per_sqkm: 2 # ScholzPhd Tab 4.3.1: 20MW/km^2
    correction_factor: 0.8855
    potential: simple # or conservative
    natura: true
    max_depth: 50
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2
  solar:
    cutout: China-2020c
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    resource_classes:
      min_cf_delta: 0.02
      n: 2
    capacity_per_sqkm: 5.1 # ScholzPhd Tab 4.3.1: 170 MW/km^2 3%
    potential: simple # or conservative
    correction_factor: 0.85
    natura: false
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2
renewable_potential_cutoff: 200 # MW, skip low potentials

heat_demand:
  start_day : "01-04" # dd-mm
  end_day : "30-09" # dd-mm
  heating_start_temp : 15.0  # c
  heating_lin_slope : 1  # slope
  heating_offet : 0  # linear model offset
solar_thermal_angle: 45

Technique:
  solar: true
  onwind: true
  offwind: true

# TODO implement consistent accounting 
# brownfield_capex:
#   existing_hydro: False
#   existing_nuclear: False
#   existing_PHS: False

bus_suffix: [""," central heat"," decentral heat"," gas"," coal"]
bus_carrier: {
    "": "AC",
    " central heat": "heat",
    " decentral heat": "heat",
    " gas": "gas",
    " coal": "coal",
}

Techs:
  ## for add carriers and generators - but ugly to have nuclear and biomass and heatpupm in vre
  vre_techs: [ "onwind","offwind","solar","solar thermal","hydroelectricity", "nuclear","biomass","beccs","heat pump","resistive heater","Sabatier","H2 CHP"]
  conv_techs: ["OCGT", "CCGT", "CHP gas", "gas boiler","coal boiler","coal power plant","CHP coal"]
  store_techs: ["H2","battery","water tanks","PHS"]
  coal_cc: true # currently myopic pathway only.  CC = co2 cap 
  hydrogen_lines: true # currently myopic pathway only

## add components (overwrites vre tech choice)
heat_coupling: false
add_biomass: True
add_hydro: True
add_H2: True
add_methanation: True
line_losses: True
no_lines: False

hydro_dams:
  dams_path: "resources/data/hydro/dams_large.csv"
  inflow_path: "resources/data/hydro/daily_hydro_inflow_per_dam_1979_2016_m3.pickle"
  inflow_date_start: "1979-01-01"
  inflow_date_end: "2017-01-01" # uses left for inclusive
  reservoir_initial_capacity_path: "resources/data/hydro/reservoir_initial_capacity.pickle"
  reservoir_effective_capacity_path: "resources/data/hydro/reservoir_effective_capacity.pickle"
  river_links_stations : "" # TODO
  p_nom_path: "resources/data/p_nom/hydro_p_nom.h5"
  p_max_pu_path: "resources/data/p_nom/hydro_p_max_pu.h5"
  p_max_pu_key : "hydro_p_max_pu"
  damn_flows_path: "resources/data/hydro/dam_flow_links.csv"
# nuclear_reactors:
#   pp_path: "resources/data/p_nom/nuclear_p_nom.csv"
H2:
  geo_storage_nodes: [ "Sichuan", "Chongqing", "Hubei", "Jiangxi", "Anhui", "Jiangsu", "Shandong", "Guangdong" ]
edge_paths:
  current: "resources/data/grids/edges_current.csv"
  current+FCG: "resources/data/grids/edges_current_FCG.csv"
  current+Neighbor: "resources/data/grids/edges_current_neighbor.csv"

solving:
  options:
#    clip_p_max_pu: 1.e-2
#    seed: 123
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: false
    min_iterations: 4
    max_iterations: 6
    clip_p_max_pu: 0.01
    skip_iterations: false
    track_iterations: false

  solver:
    name: gurobi
    options: gurobi-default
  gurobi_hpc_tunnel:
    use_tunnel: True
    tunnel_port: 27000
    timeout_s: 15
    login_node: "03"

  solver_options:
    highs-default:
      # refer to https://ergo-code.github.io/HiGHS/options/definitions.html#solver
      threads: 4
      solver: "ipm"
      run_crossover: "off"
      small_matrix_value: 1e-6
      large_matrix_value: 1e9
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      ipm_optimality_tolerance: 1e-4
      parallel: "on"
      random_seed: 123
    gurobi-default:
      threads: 8
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-6
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
      DualReductions: 0
#      BarConvTol: 1.e-6
#      Seed: 123
#      AggFill: 0
#      PreDual: 0
#      seed: 10              # Consistent seed for all plattforms
    gurobi-numeric-focus:
      name: gurobi
      NumericFocus: 3       # Favour numeric stability over speed
      method: 2             # barrier
      crossover: 0          # do not use crossover
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-4
      OptimalityTol: 1.e-4
      ObjScale: -0.5
      threads: 8
      Seed: 123
    gurobi-fallback:        # Use gurobi defaults
      name: gurobi
      crossover: 0
      method: 2             # barrier
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-5
      OptimalityTol: 1.e-5
      Seed: 123
      threads: 8
    cplex-default:
      threads: 4
      lpmethod: 4 # barrier
      solutiontype: 2 # non basic solution, ie no crossover
      barrier.convergetol: 1.e-5
      feasopt.tolerance: 1.e-6
    cbc-default: {} # Used in CI
    glpk-default: {} # Used in CI

  mem: 80000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2

lines:
  line_volume_limit_max: 5.e+15   #line_volume_limit is set = factor * max
  line_length_factor: 1.25
security:
  line_margin: 70 # max percent of line capacity

existing_capacities:
  add: True 
  grouping_years: [1980,1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019, 2020, 2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060]
  threshold_capacity: 1 # TODO UNIT
  techs: ['coal','CHP coal', 'CHP gas', 'OCGT','solar', 'solar thermal', 'onwind', 'offwind','coal boiler','ground heat pump','nuclear']

fetch_regions:
  simplify_tol: 0.5