# 中国省份配置文件
# Province configuration for China

# 省份列表 - 基于 REGIONAL_GEO_TIMEZONES_DEFAULT
provinces:
  - "Anhui"
  - "Beijing"
  - "Chongqing"
  - "Fujian"
  - "Gansu"
  - "Guangdong"
  - "Guangxi"
  - "Guizhou"
  - "Hainan"
  - "Hebei"
  - "Heilongjiang"
  - "Henan"
  # - "Hubei"
  # - "Hunan"
  # - "InnerMongolia"
  # - "Jiangsu"
  # - "Jiangxi"
  # - "Jilin"
  # - "Liaoning"
  # - "Ningxia"
  # - "Qinghai"
  # - "Shaanxi"
  # - "Shandong"
  # - "Shanghai"
  # - "Shanxi"
  # - "Sichuan"
  # - "Tianjin"
  # - "Tibet"
  # - "Xinjiang"
  # - "Yunnan"
  # - "Zhejiang"

# # 省份分离配置（目前仅作为配置框架）
# splits:
#   # 示例：内蒙古分为东西两部分（功能待实现）
#   "InnerMongolia":
#     - "InnerMongolia East"
#     - "InnerMongolia West"

# 省份分组配置（可选）
groups:
  # 按地理区域分组
  north:
    - "Beijing"
    - "Tianjin"
    - "Hebei"
    - "Shanxi"
    - "InnerMongolia"
    - "Liaoning"
    - "Jilin"
    - "Heilongjiang"
  
  east:
    - "Shanghai"
    - "Jiangsu"
    - "Zhejiang"
    - "Anhui"
    - "Fujian"
    - "Jiangxi"
    - "Shandong"
  
  central:
    - "Henan"
    - "Hubei"
    - "Hunan"
  
  south:
    - "Guangdong"
    - "Guangxi"
    - "Hainan"
  
  southwest:
    - "Chongqing"
    - "Sichuan"
    - "Guizhou"
    - "Yunnan"
    - "Tibet"
  
  northwest:
    - "Shaanxi"
    - "Gansu"
    - "Qinghai"
    - "Ningxia"
    - "Xinjiang"
