
transmission_efficiency:
  DC:
    efficiency_static: 0.98
    efficiency_per_1000km: 0.977
  H2 pipeline:
    efficiency_static: 1
    efficiency_per_1000km: 0.979
    compression_per_1000km: 0.019

chp_parameters:
  eff_el: 0.3978
  eff_th: 0.5304

solar_cf_correction: 0.85
time_dep_hp_cop: True
# standing losses for thermal storage
water_tanks:
  tes_tau:
    decentral: 3. # days
    central: 180 # days

electricity:
  max_hours:
    battery: 6
    H2: 168
  min_charge:
    battery: 0.1 # fraction of e_nom
```


# TODO move to brownfield?
hydro:
  hydro_capital_cost: True
  marginal_cost: 
    reservoir: 0. # EUR/MWh
  PHS_max_hours: 24 # hours

fossil_ramps:
  coal:
    ramp_limit_up: 0.5 # fraction of p_nom per hour
    ramp_limit_down: 0.5 # fraction of p_nom per hour
# overly simplistic to not have unit commitment
nuclear_reactors:
  p_max_pu: 0.88 # fraction of p_nom, after IEAE
  p_min_pu: 0.7 # fraction of p_nom
costs:
  discountrate: 0.06
  social_discount_rate: 0.02 # social discountrate
  USD2013_to_EUR2013: 0.9189 # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html
  pv_utility_fraction: 1 # the fraction that will not be residential