sort:
  direction: null 
  type: natural 
  by: filename 
  sections: last 
  ignore_case: true 
nav:
  PyPSA-PIK: index.md
  Model: model.md
  Getting started: installation
  Configuration: configuration.md
  Tutorials: tutorials
  Reference: reference

