name: Deploy Documentation

on:
  push:
    branches:
      - main
      - fix_docu
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy documentation for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          mike deploy --push --update-aliases latest main
          mike set-default --push latest

      - name: Deploy documentation for fix_docu branch
        if: github.ref == 'refs/heads/fix_docu'
        run: |
          mike deploy --push --update-aliases dev fix_docu

      - name: Deploy documentation for release tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mike deploy --push --update-aliases "$VERSION" stable
          mike set-default --push stable

      - name: Deploy documentation for PR preview
        if: github.event_name == 'pull_request'
        run: |
          mkdocs build
